import { createWalletClient, custom, defineChain, parseEther } from 'viem'
import './style.css'

const chain = defineChain({ id: 61999, name: 'GenLayer Studionet', nativeCurrency: { name: 'GEN', symbol: 'GEN', decimals: 18 }, rpcUrls: { default: { http: [import.meta.env.VITE_REDEEM_RPC_URL || 'https://studio.genlayer.com/api'] } } })
const address = import.meta.env.VITE_REDEEM_CONTRACT_ADDRESS
const abi = [
  { name:'get_guarantee', type:'function', stateMutability:'view', inputs:[{name:'guarantee_id',type:'uint256'}], outputs:[{type:'string'}] },
  { name:'get_status', type:'function', stateMutability:'view', inputs:[{name:'guarantee_id',type:'uint256'}], outputs:[{type:'uint8'}] },
  { name:'status_label', type:'function', stateMutability:'view', inputs:[{name:'guarantee_id',type:'uint256'}], outputs:[{type:'string'}] },
  { name:'open_redemption', type:'function', stateMutability:'nonpayable', inputs:[{name:'guarantee_id',type:'uint256'}], outputs:[] },
  { name:'evaluate_redemption', type:'function', stateMutability:'nonpayable', inputs:[{name:'guarantee_id',type:'uint256'}], outputs:[] },
  { name:'finalize_redemption', type:'function', stateMutability:'nonpayable', inputs:[{name:'guarantee_id',type:'uint256'}], outputs:[] },
  { name:'create_guarantee', type:'function', stateMutability:'payable', inputs:[{name:'beneficiary',type:'address'},{name:'title',type:'string'},{name:'terms',type:'string'},{name:'coverage_start',type:'uint256'},{name:'coverage_end',type:'uint256'},{name:'evaluation_earliest_at',type:'uint256'},{name:'claim_deadline',type:'uint256'},{name:'source_urls',type:'string'},{name:'outcome_codes',type:'string'},{name:'payout_bps',type:'string'}], outputs:[] },
  { name:'challenge_redemption', type:'function', stateMutability:'payable', inputs:[{name:'guarantee_id',type:'uint256'},{name:'reason',type:'string'}], outputs:[] },
]
const app = document.querySelector('#app')
app.innerHTML = `<main><nav><span class="mark">REDEEM</span><button id="connect">Connect wallet</button></nav><section class="hero"><p class="eyebrow">ESCROW-BACKED GUARANTEES</p><h1>Promises, backed<br><em>before they break.</em></h1><p class="lede">Turn a promise into a funded, publicly verifiable guarantee. GenLayer interprets the evidence. Deterministic code pays.</p></section><section class="panel"><h2>Create guarantee</h2><div class="form"><input id="beneficiary" placeholder="Beneficiary address"><input id="title" placeholder="Title"><input id="terms" placeholder="Frozen terms"><input id="escrow" placeholder="Escrow in GEN" type="number"><input id="sources" placeholder="HTTPS sources, one per line"><input id="outcomes" placeholder="Outcome codes, one per line"><input id="payouts" placeholder="Payout BPS, comma-separated"></div><button id="create">Fund guarantee</button></section><section class="panel"><h2>Manage redemption</h2><div class="lookup"><input id="id" type="number" min="1" placeholder="Guarantee ID"><button id="lookup">Read contract</button></div><input id="reason" placeholder="Challenge reason"><input id="bond" placeholder="Challenge bond in GEN" type="number"><div class="actions"><button id="open">Open redemption</button><button id="evaluate">Evaluate</button><button id="challenge">Challenge</button><button id="finalize">Finalize</button></div><pre id="result">Connect a wallet to begin.</pre></section><footer>Studionet · Chain 61999 · AI classifies. Deterministic code pays.</footer></main>`
let wallet
document.querySelector('#connect').onclick = async () => { if (!window.ethereum) return alert('Install an external wallet such as MetaMask.'); wallet = createWalletClient({ chain, transport: custom(window.ethereum) }); const [account] = await wallet.requestAddresses(); document.querySelector('#connect').textContent = account.slice(0,6)+'…'+account.slice(-4) }
document.querySelector('#lookup').onclick = async () => { if (!address) return document.querySelector('#result').textContent='No deployed contract configured. Set VITE_REDEEM_CONTRACT_ADDRESS.'; try { const r = await wallet?.readContract({ address, abi, functionName:'get_guarantee', args:[BigInt(document.querySelector('#id').value)] }); document.querySelector('#result').textContent = r || 'No guarantee found.' } catch(e) { document.querySelector('#result').textContent = e.shortMessage || e.message } }
document.querySelector('#create').onclick = async () => { if (!wallet || !address) return document.querySelector('#result').textContent='Connect a wallet and configure the deployed contract.'; try { const [account] = await wallet.getAddresses(); const now=Math.floor(Date.now()/1000); const hash=await wallet.writeContract({address,abi,functionName:'create_guarantee',args:[document.querySelector('#beneficiary').value,document.querySelector('#title').value,document.querySelector('#terms').value,BigInt(now),BigInt(now+86400),BigInt(now),BigInt(now+172800),document.querySelector('#sources').value,document.querySelector('#outcomes').value,document.querySelector('#payouts').value],value:parseEther(document.querySelector('#escrow').value),account,chain}); document.querySelector('#result').textContent=`Submitted create_guarantee: ${hash}` } catch(e) { document.querySelector('#result').textContent=e.shortMessage||e.message } }
async function write(functionName, extra=[], value=0n) { if (!wallet || !address) return document.querySelector('#result').textContent='Connect a wallet and configure VITE_REDEEM_CONTRACT_ADDRESS.'; try { const [account] = await wallet.getAddresses(); const hash = await wallet.writeContract({ address, abi, functionName, args:[BigInt(document.querySelector('#id').value),...extra], value, account, chain }); document.querySelector('#result').textContent = `Submitted ${functionName}: ${hash}` } catch(e) { document.querySelector('#result').textContent = e.shortMessage || e.message } }
document.querySelector('#open').onclick = () => write('open_redemption')
document.querySelector('#evaluate').onclick = () => write('evaluate_redemption')
document.querySelector('#finalize').onclick = () => write('finalize_redemption')
document.querySelector('#challenge').onclick = () => write('challenge_redemption', [document.querySelector('#reason').value], parseEther(document.querySelector('#bond').value || '0'))
