import './style.css';
import {createClient,createAccount} from 'genlayer-js';
import {studionet} from 'genlayer-js/chains';
import {CHAIN_ID,bond,guards,lifecycle} from './protocol.js';
const app=document.querySelector('#app'), address=import.meta.env.VITE_REDEEM_CONTRACT_ADDRESS||''; let client,wallet;
const routes=['/','/issue','/guarantees','/my-rights','/my-issued','/activity','/about'];
const qs=s=>document.querySelector(s);
function shell(body){app.innerHTML='<main><nav><a class="mark" href="/" data-link>REDEEM</a><div class="links">'+routes.map(r=>'<a href="'+r+'" data-link>'+(r==='/'?'Home':r.slice(1).replaceAll('-',' '))+'</a>').join('')+'</div><button id="connect">'+(wallet||'Connect wallet')+'</button></nav>'+body+'<footer>Studionet · '+CHAIN_ID+'</footer></main>';document.querySelectorAll('[data-link]').forEach(a=>a.onclick=e=>{e.preventDefault();history.pushState({},'',a.getAttribute('href'));render()});qs('#connect').onclick=connect}
async function connect(){if(!window.ethereum)return alert('Install an external wallet.');if(Number(await window.ethereum.request({method:'eth_chainId'}))!==CHAIN_ID)return alert('Switch to Studionet 61999.');[wallet]=await window.ethereum.request({method:'eth_requestAccounts'});client=createClient({chain:studionet,provider:window.ethereum,account:createAccount(wallet)});render()}
const read=(functionName,args=[])=>{if(!client||!address)throw Error('Connect wallet and configure VITE_REDEEM_CONTRACT_ADDRESS');return client.readContract({address,functionName,args})};
async function write(functionName,args=[],value=0n){const hash=await client.writeContract({address,functionName,args,value}),receipt=await client.waitForTransactionReceipt({hash}),state=lifecycle(receipt);if(state==='ERROR'||state==='UNDETERMINED')throw Error('Execution '+state.toLowerCase());return receipt}
async function detail(id){const names={open_redemption:'open',evaluate_redemption:'evaluate',challenge_redemption:'challenge',resolve_challenge:'resolve',finalize_redemption:'finalize',finalize_inconclusive:'inconclusive',finalize_stalled_challenge:'stalled',reclaim_expired_guarantee:'reclaim'};shell('<header class="page"><p class="eyebrow">DETAIL</p><h1>#'+id+'</h1></header><section class="panel"><p id="record">Loading…</p><div class="actions">'+Object.keys(names).map(a=>'<button data-action="'+a+'" disabled>'+a.replaceAll('_',' ')+'</button>').join('')+'</div></section>');try{const g=await read('get_guarantee',[Number(id)]),gate=guards(g,wallet,Date.now()/1000);qs('#record').textContent=JSON.stringify(g);document.querySelectorAll('[data-action]').forEach(b=>{const k=names[b.dataset.action];b.disabled=!gate[k];if(k==='challenge')b.textContent+=' ('+bond(g.escrow_total)+' wei)';b.onclick=async()=>{try{b.disabled=true;await write(b.dataset.action,[Number(id)],k==='challenge'?bond(g.escrow_total):0n);detail(id)}catch(e){b.disabled=false;b.textContent='Blocked: '+e.message}}})}catch(e){qs('#record').textContent='Unavailable: '+e.message}}
async function collection(title,method){shell('<header class="page"><h1>'+title+'</h1></header><section class="panel"><p id="records">Loading…</p></section>');try{const rows=await read(method||'list_guarantees',method?[wallet,0,25]:[0,25]);qs('#records').textContent=JSON.stringify(rows)}catch(e){qs('#records').textContent='Unavailable: '+e.message}}
function issue(){shell('<header class="page"><h1>Fund a guarantee.</h1></header><section class="panel"><form id="issue-form" class="form"><label>Beneficiary<input name="beneficiary" required></label><label>Title<input name="title" required></label><label>Terms<textarea name="terms" required></textarea></label><label>Escrow wei<input name="escrow" type="number" required></label><label>Source rules JSON<textarea name="sources" required>[{"label":"Status","url":"https://example.com/status","authority":"PRIMARY","required":true}]</textarea></label><label>Outcome rules JSON<textarea name="outcomes" required>[{"code":"MET","description":"Met","payout_bps":10000},{"code":"MISS","description":"Missed","payout_bps":0}]</textarea></label><button>Fund</button><p id="issue-status"></p></form></section>');qs('#issue-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await write('create_guarantee',[f.get('beneficiary'),f.get('title'),f.get('terms'),0,4102444800,0,4102444800,BigInt(f.get('escrow')),f.get('sources'),f.get('outcomes')],BigInt(f.get('escrow')));qs('#issue-status').textContent='Executed successfully';}catch(x){qs('#issue-status').textContent='Blocked: '+x.message}}}
function render(){const p=location.pathname;if(p==='/')return shell('<section class="hero"><h1>Promises, backed<br><em>before they break.</em></h1><a class="button" href="/issue" data-link>Issue a guarantee</a></section>');if(p==='/issue')return issue();if(p.startsWith('/guarantees/'))return detail(p.split('/').pop());if(p==='/my-rights')return collection('My rights','list_guarantees_by_beneficiary');if(p==='/my-issued')return collection('My issued','list_guarantees_by_issuer');if(p==='/about')return shell('<header class="page"><h1>About Redeem</h1></header>');return collection(p.slice(1))}
window.onpopstate=render;render();
