export const CHAIN_ID=61999
export const STATUSES=['ACTIVE','REDEMPTION_OPEN','RETRYABLE','PROVISIONAL','CHALLENGED','SETTLED_PAID','SETTLED_DENIED','EXPIRED_REFUNDED','INCONCLUSIVE_REFUNDED']
const GEN_BASE=1000000000000000000n
export function parseGen(value){const text=String(value).trim();if(!/^\d+(\.\d{1,18})?$/.test(text))throw Error('Enter a valid GEN amount');const [whole,fraction='']=text.split('.');return BigInt(whole)*GEN_BASE+BigInt((fraction+'0'.repeat(18)).slice(0,18))}
export function formatGen(value){const raw=BigInt(value);const whole=raw/GEN_BASE;const fraction=(raw%GEN_BASE).toString().padStart(18,'0').replace(/0+$/,'');return fraction?`${whole}.${fraction}`:String(whole)}
export function buildPayload(v){if(!v.beneficiary||!v.title||!v.terms||v.sources.length<1||v.sources.length>4||v.outcomes.length<2||v.outcomes.length>5)throw Error('Incomplete guarantee');const escrow=BigInt(v.escrowWei);return [v.beneficiary,v.title,v.terms,BigInt(v.coverageStart),BigInt(v.coverageEnd),BigInt(v.evaluationAt),BigInt(v.claimDeadline),escrow,JSON.stringify(v.sources),JSON.stringify(v.outcomes)]}
export function bond(total){return BigInt(total)*500n/10000n}
export function buildRecurringPayload(v,now=BigInt(Math.floor(Date.now()/1000))){const count=Number(v.epochCount);if(!Number.isInteger(count)||count<2||count>12)throw Error('Recurring guarantees require 2–12 epochs');if(v.firstStart===undefined||v.firstStart===null||v.firstStart==='')throw Error('Choose a first coverage start in the future');let firstStart;try{firstStart=BigInt(v.firstStart)}catch{throw Error('Choose a valid first coverage start in the future')}if(firstStart<=BigInt(now))throw Error('First coverage start must be in the future');const total=BigInt(v.escrowWei);if(total<=0n||total%BigInt(count)!==0n)throw Error('Total liability must divide evenly across epochs');if((total/BigInt(count))*500n/10000n===0n)throw Error('Per-epoch liability is too small for its challenge bond');if(BigInt(v.epochDuration)<=0n||BigInt(v.claimGrace)<=0n)throw Error('Epoch duration and claim grace must be positive');if(!v.beneficiary||!v.title||!v.terms||v.sources.length<1||v.sources.length>4||v.outcomes.length<2||v.outcomes.length>5)throw Error('Incomplete recurring guarantee');return [v.beneficiary,v.title,v.terms,firstStart,BigInt(v.epochDuration),count,BigInt(v.claimGrace),total,JSON.stringify(v.sources),JSON.stringify(v.outcomes)]}
export function recurringTotals(epochs){return epochs.reduce((a,e)=>({paid:a.paid+BigInt(e.paid||0),refunded:a.refunded+BigInt(e.refunded||0),unallocated:a.unallocated+BigInt(e.liability||0)-BigInt(e.paid||0)-BigInt(e.refunded||0)}),{paid:0n,refunded:0n,unallocated:0n})}
export function lifecycle(receipt){if(!receipt)return 'CONSENSUS_PENDING';const result=receipt.resultName??receipt.result_name??receipt.consensus_data?.result_name;const undecided=['MAJORITY_DISAGREE','NO_MAJORITY','DISAGREE','TIMEOUT','DETERMINISTIC_VIOLATION'];if(undecided.includes(result)||['UNDETERMINED','VALIDATORS_TIMEOUT','LEADER_TIMEOUT'].includes(receipt.statusName??receipt.status_name))return 'UNDETERMINED';const leader=receipt.consensus_data?.leader_receipt?.[0]??receipt.leader_receipt?.[0];const execution=receipt.txExecutionResultName??receipt.tx_execution_result_name??receipt.executionResult??receipt.execution_result??receipt.consensus_data?.leader_receipt?.[0]?.execution_result??receipt.leader_receipt?.[0]?.execution_result??leader?.result?.status??leader?.result;const failed=['FINISHED_WITH_ERROR','ERROR','FAILURE','REVERT','revert'];if(failed.includes(execution)||execution===2||execution==='2'||result==='FAILURE')return 'ERROR';const succeeded=['FINISHED_WITH_RETURN','SUCCESS','return'];if(succeeded.includes(execution)||execution===1||execution==='1'||result==='SUCCESS')return 'EXECUTED';return 'FINALIZED'}
export function guards(g,wallet,now){const off={open:false,evaluate:false,challenge:false,finalize:false,resolve:false,inconclusive:false,stalled:false,reclaim:false};if(!g||!wallet)return off;const me=wallet.toLowerCase(),issuer=me===g.issuer.toLowerCase(),beneficiary=me===g.beneficiary.toLowerCase();const grace=604800,recovery=3600,interval=3600;const retry=(start,last)=>now>=last+interval&&(now<start+grace||now<start+grace+recovery);return {open:g.status===0&&beneficiary&&now>=Number(g.evaluation_earliest_at)&&now<=Number(g.claim_deadline),evaluate:(g.status===1||g.status===2)&&retry(Number(g.opened_at),Number(g.last_review_attempt_at||0)),challenge:g.status===3&&(issuer||beneficiary)&&now<Number(g.challenge_deadline),finalize:g.status===3&&now>=Number(g.challenge_deadline),resolve:g.status===4&&retry(Number(g.challenge_opened_at),Number(g.last_challenge_attempt_at||0)),inconclusive:g.status===2&&now>=Number(g.opened_at)+grace+recovery&&now>=Number(g.last_review_attempt_at||0)+interval,stalled:g.status===4&&now>=Number(g.challenge_opened_at)+grace+recovery&&now>=Number(g.last_challenge_attempt_at||0)+interval,reclaim:g.status===0&&now>Number(g.claim_deadline)}}
