import { createClient, createAccount } from "genlayer-js";
import { CalldataAddress, ExecutionResult, TransactionStatus } from "genlayer-js/types";
import { studionet } from "genlayer-js/chains";
const address = "0x32Eb76d30f27856C2310D8f3C4d244B1fEEBBcb2";
const issuer = createClient({chain:studionet,account:createAccount(process.env.REDEEM_ISSUER_KEY)});
const beneficiary = createClient({chain:studionet,account:createAccount(process.env.REDEEM_BENEFICIARY_KEY)});
const read=createClient({chain:studionet}); const safe=(x)=>JSON.stringify(x,(_,v)=>typeof v==='bigint'?v.toString():v);
const wait=async(c,h)=>{const r=await c.waitForTransactionReceipt({hash:h,status:TransactionStatus.FINALIZED,fullTransaction:true,retries:120,interval:5000});const consensus=r.result_name??r.resultName;const execution=r.tx_execution_result_name??r.txExecutionResultName;const leader=r.leader_receipt?.[0]?.result;console.log('finalized',h,consensus,execution??leader?.status??'return');if(consensus!=='MAJORITY_AGREE')throw Error(`undetermined ${h} consensus=${consensus}`);if(execution&&execution!==ExecutionResult.FINISHED_WITH_RETURN)throw Error(`execution ${execution} ${h}`);if(leader?.status&&leader.status!=='return')throw Error(`execution ${leader.status} ${h}`);return r};
const call=async(c,name,args=[],value=0n)=>{const h=await c.writeContract({address,functionName:name,args,value});await wait(c,h);console.log(name,h);return h};
const now=Math.floor(Date.now()/1000), end=BigInt(now+7200), src=(name)=>JSON.stringify([{label:name,url:`https://raw.githubusercontent.com/Ifem1/Redeem/716a1e9cd9083f0a762d54fbee360f8157a8c149/demo-evidence/${name}.json`,authority:'PRIMARY',required:true}]);
const outcomes=JSON.stringify([{code:'MET',description:'Evidence states the service condition was met.',payout_bps:0},{code:'BREACH',description:'Evidence states the service condition was breached.',payout_bps:10000}]);
const baddr=new CalldataAddress(Uint8Array.from(Buffer.from(issuer.account.address.slice(2),'hex'))); const benaddr=new CalldataAddress(Uint8Array.from(Buffer.from(beneficiary.account.address.slice(2),'hex')));
const before=await read.readContract({address,functionName:'get_contract_accounting',args:[]});const counter=Number(await read.readContract({address,functionName:'get_guarantee_counter',args:[]}));
async function cycle(label,evidence,challenger){const t=Math.floor(Date.now()/1000);const deadline=BigInt(t+7200);const id=Number(await read.readContract({address,functionName:'get_guarantee_counter',args:[]}))+1;await call(issuer,'create_guarantee',[benaddr,label,'Classify only from the frozen PRIMARY evidence. Return MET for explicit MET/operational evidence and BREACH for explicit BREACH/failed evidence.',BigInt(t-900),BigInt(t-600),BigInt(t-300),deadline,20000000000000000n,src(evidence),outcomes],20000000000000000n);await call(beneficiary,'open_redemption',[BigInt(id)]);await call(issuer,'evaluate_redemption',[BigInt(id)]);console.log('provisional',safe(await read.readContract({address,functionName:'get_guarantee',args:[BigInt(id)]})));await call(challenger,'challenge_redemption',[BigInt(id)],1000000000000000n);await call(issuer,'resolve_challenge',[BigInt(id)]);console.log('final',safe(await read.readContract({address,functionName:'get_guarantee',args:[BigInt(id)]})));console.log('manifest-primary',safe(await read.readContract({address,functionName:'get_evidence_manifest',args:[BigInt(id),0,1]})));console.log('manifest-challenge',safe(await read.readContract({address,functionName:'get_evidence_manifest',args:[BigInt(id),1,1]})));return id}
async function finishExisting(id,challenger){await call(beneficiary,'open_redemption',[BigInt(id)]);await call(issuer,'evaluate_redemption',[BigInt(id)]);console.log('provisional',safe(await read.readContract({address,functionName:'get_guarantee',args:[BigInt(id)]})));await call(challenger,'challenge_redemption',[BigInt(id)],1000000000000000n);await call(issuer,'resolve_challenge',[BigInt(id)]);console.log('final',safe(await read.readContract({address,functionName:'get_guarantee',args:[BigInt(id)]})));console.log('manifest-primary',safe(await read.readContract({address,functionName:'get_evidence_manifest',args:[BigInt(id),0,1]})));console.log('manifest-challenge',safe(await read.readContract({address,functionName:'get_evidence_manifest',args:[BigInt(id),1,1]})))}
await cycle('Redeem Live Verification A — Service Met','cycle-met',beneficiary);await cycle('Redeem Live Verification B — Service Breach','cycle-breach',issuer);console.log('before',safe(before));console.log('after',safe(await read.readContract({address,functionName:'get_contract_accounting',args:[]})));console.log('startedAtCounter',counter);
